branch-defaults:
  master:
    environment: calculator
environment-defaults:
  calculator:
    branch: null
    repository: null
global:
  application_name: calculator
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Docker running on
    64bit Amazon Linux/2.7.0
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
